apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panda-wiki.fullname" . }}-app
  labels:
    {{- include "panda-wiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "panda-wiki.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "panda-wiki.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: app
          image: {{ include "panda-wiki.image" (dict "global" .Values.global "local" .Values.app) | quote }}
          ports:
            - containerPort: 80
              name: http
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panda-wiki.fullname" . }}-app
  labels:
    {{- include "panda-wiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "panda-wiki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
