{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "panda-wiki.fullname" . }}-minio
  labels:
    {{- include "panda-wiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: {{ include "panda-wiki.fullname" . }}-minio
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      {{- include "panda-wiki.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "panda-wiki.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: {{ include "panda-wiki.image" (dict "global" .Values.global "local" .Values.minio) | quote }}
          command:
            - minio
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "http://{{ .Values.istio.gateway.host }}/static-file/"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.accessKey | quote }}
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "panda-wiki.fullname" . }}-secrets
                  key: s3-secret-key
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.minio.storage.storageClassName }}
        storageClassName: {{ .Values.minio.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.storage.size | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panda-wiki.fullname" . }}-minio
  labels:
    {{- include "panda-wiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "panda-wiki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
