apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panda-wiki.fullname" . }}-secrets
  labels:
    {{- include "panda-wiki.labels" . | nindent 4 }}
type: Opaque
stringData:
  nats-password: {{ .Values.secrets.natsPassword | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
  qdrant-api-key: {{ .Values.secrets.qdrantApiKey | quote }}
