apiVersion: v1
kind: Service
metadata:
  name: {{ include "newapi.headlessServiceName" . }}
  labels:
    app: {{ include "newapi.name" . }}
    component: application
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "newapi.name" . }}
    component: application
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
