{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newapi.fullname" . }}-redis
  labels:
    app: {{ include "newapi.name" . }}
    component: redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ include "newapi.name" . }}
    component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
{{- end }}