{{- if and .Values.redis.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newapi.redis.authSecretName" . }}
type: Opaque
stringData:
  password: {{ required "redis.auth.password is required when redis.auth.enabled=true and no redis.auth.existingSecret.name is set" .Values.redis.auth.password | quote }}
{{- end }}